# Use node.js environment
language: node_js

# Test only version 7
node_js: "7"

# Define different groups of environment variables
env:
  - AUTH=false
  - AUTH=true USER=test PASSWORD=secret

# Install dependencies
install: npm install

# Start service
before_script: npm start

# Run the tests
script:
  - npm run lint
  - npm test

# Limit build to master branch
branches:
  only:
    - master

# Sent notifications via mail
notifications:
  email:
    - twiens@mail.uni-paderborn.de